---
name: VanillaEnchantments
version: 4.0.0
api:
- 3.9.3
author: NajeeSlays
website: "https://github.com/TheAz928/VanillaEnchantments"
main: vanilla\Core
description: "Vanilla Enchants by NajeeSlays"

...
