---
name: VanillaEnchants
version: 1.0.3_Alpha_8
api:
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
author: TheAz928
main: VanillaEnchants\Core
description: "Implement vanilla enchants in your PocketMine-MP (BedRockEngine) server!"

...